package com.project.zpo.Tables;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;
import java.util.List;

/**
 * Entity class representing a group of students.
 * Each group has a unique name and contains a list of students.
 * The class implements the Serializable interface to enable object serialization.
 * <p>
 * In database, it is represented as table of fields: [id, name]
 * with relation one-to-many with table students.
 * <p>
 * Constructors, getters and setters are generated by Lombok annotations.
 * @see Student
 */
@Entity
@Table(name = "student_group")
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Group implements Serializable {

    /**
     * Unique auto-incremented identifier for the group.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique name of the group.
     */
    @Column(unique = true)
    private String name;

    /**
     * List of students belonging to the group.
     * Relation one group to many students.
     * @see Student
     */
    @OneToMany(targetEntity = Student.class, mappedBy = "studentGroup")
    @JsonIgnore
    private List<Student> students;

}
