package com.project.zpo.RequestsAndResponses;

import lombok.AllArgsConstructor;
import lombok.Getter;

import java.time.LocalDate;
import java.util.List;

/**
 * Data Transfer Object (DTO) representing a request for attendance, including the date and a list of student attendance data.
 * Constructor and getters are generated by Lombok annotations.
 */
@Getter
@AllArgsConstructor
public class AttendanceRequest {

    private LocalDate date;
    private List<StudentAttendanceData> attendanceData;

}
