package com.project.zpo.RequestsAndResponses;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Data Transfer Object (DTO) representing basic student information sent via REST.
 * Constructors, getters and setters are generated by Lombok annotations.
 */
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
public class BasicStudentResponse {

    private Long album;
    private String firstName;
    private String lastName;

}
