package com.project.zpo.RequestsAndResponses;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

/**
 * Data Transfer Object (DTO) representing a response containing group information along with a list of basic student responses.
 * Constructor, getters and setters are generated by Lombok annotations.
 */
@AllArgsConstructor
@Getter
@Setter
public class GroupResponse {

    private Long id;
    private String name;
    private List<BasicStudentResponse> students;

}
