package com.project.zpo.RequestsAndResponses;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

/**
 * Data Transfer Object (DTO) representing group attendance response, containing a list of student responses.
 * Constructor, getters and setters are generated by Lombok annotations.
 */
@AllArgsConstructor
@Getter
@Setter
public class GroupAttendanceResponse {

    private List<StudentResponse> studentResponseList;

}
