package com.project.zpo.RequestsAndResponses;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Data Transfer Object (DTO) representing a request to change a student's group.
 * Constructors, getters and setters are generated by Lombok annotations.
 */
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class GroupChangeRequest {

    private Long newGroupId;
    private Long studentAlbum;

}
