package com.project.zpo.RequestsAndResponses;

import com.project.zpo.Tables.Attendance;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.util.List;

/**
 * Data Transfer Object (DTO) representing a request containing term information along with a list of attendances.
 * Constructors, getters and setters are generated by Lombok annotations.
 */
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class TermRequest {
    private Long id;
    private LocalDate date;
    private List<Attendance> attendances;

}
