package com.project.zpo.RequestsAndResponses;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * Data Transfer Object (DTO) representing a request for whole group attendance data, including the group ID and the date.
 * Constructor and getters are generated by Lombok annotations.
 */
@AllArgsConstructor
@NoArgsConstructor
@Getter
public class WholeGroupAttendanceRequest {

    private Long groupId;
    private LocalDate date;

}
